
## default connection pool
debug: true
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://mouse.db.elephantsql.com/embtszfx
    username: embtszfx
    password: cSJdByTBzKK7BgesMyme8X3JYegZbRAu
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  data:
    mongodb:
      uri: mongodb+srv://user:pwd@atlascluster.a0y9dkm.mongodb.net/test
      database: test
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
okta:
  oauth2:
    issuer: ${env.ISSUER} #dev-98888155.okta.com
    client-id: ${env.CLIENT_ID} #0oa8tbhsa7ecapYI65d7
    client-secret: ${env.CLIENT_SECRET} #pNijfBuFXsPKybqBaMrDc4ZL88sIoXihbMvTk89K
#    scope: openid,courses,email,profile
#    groupsClaim: grp
.env:
  filename: .okta.env